### PR TITLE
Cleaning up some infrastructure

### PR DESCRIPTION
**Pull request by jsignell**
- Using autover exclusively
 - Migrating to setup.py
 - Reformatting to make cmd slightly more DRY

### CODE REVIEW

**Comment by jsignell** [comment]
This one is also ready @jbednar if you have any comments

**Comment by philippjfr** [comment]
>that should be called either sphinx_pyct_default_theme or sphinx_pyviz_theme.

I'd vote for ``sphinx_pyviz_theme`` and we should rename the repo soon then and release under the new name.

**Comment by jbednar** [comment]
Note that those are two different things -- sphinx_pyviz_theme is for our own projects; sphinx_pyct_theme would be a generic theme that tries not to look too much like a pyviz project so that people can use pyct without appearing to impersonate us!  I just am not sure which one should be hardcoded in pyct; I assume sphinx_pyct_theme would be the one hardcoded, and each project would instead specify sphinx_pyviz_theme.

**Comment by jsignell** [comment]
So the docs for pyct shouldn't look like the rest of the pyviz docs? I understand the wish for a generic theme, but that wouldn't be what we use for the pyct site right?

**Comment by jsignell** [comment]
Note that the pyct site doesn't exist yet, so this is speculative

**Comment by jbednar** [comment]
No, the docs for pyct should look about the same as the rest of the pyviz docs.  But the docs for some random site created by a non-pyviz user using the defaults should not look like pyviz docs, they should look distinct.  So I guess I should have proposed sphinx_nbsite_theme instead of sphinx_pyct_theme (sorry for the confusion between pyct and nbsite!); pyct and nbsite (as pyviz projects) should use sphinz_pyviz_theme, but nbsite should default to something other than sphinx_pyviz_theme when it is used outside of pyviz.  For one thing, that way we can change the look and feel of pyviz projects whenever we want without affecting any other nbsite or pyct users.

**Comment by jsignell** [comment]
yes I agree - just trying to check my understanding

**Pull request merged**
