### PR TITLE
Support 'test data'.

### PR DESCRIPTION
**Pull request by ceball**
For testing that examples work at all (e.g. on travis), we can't always use full datasets (e.g. takes too long to download data, or requires too many resources to run example with the full dataset).

This PR supports 'test data' in pyct's fetch-data command, allowing to specify a small version of the full dataset. The idea is that example authors should provide a small test version of the data if the full data is big, and the example should work (i.e. run ok) with the small data.

If pyct.cmd is called with `--use-test-data`, then if a dataset contains `test_files`, these will be copied in place of `files`. The test files should exist already in the data directory (i.e. be committed to the examples/data directory in git).

Example:

```yaml
data:
  - url: https://s3.amazonaws.com/datashader-data/nyc_taxi_wide.parq
    title: 'NYC Taxi Data'
    files:
      - nyc_taxi_wide.parq
    test_files:
      - nyc_taxi_50k.parq
```

```sh
$ pyviz fetch-data --path=examples --use-test-data
[...]
Copying test data file '/home/ceball/code/pyviz/pyviz3/examples/data/nyc_taxi_50k.parq' to '/home/ceball/code/pyviz/pyviz3/examples/data/nyc_taxi_wide.parq'
[...]
```

Behavior should be same as for downloading, e.g. skips existing files by default:

```sh
$ pyviz fetch-data --path=examples --use-test-data
[...]
Skipping NYC Taxi Data
[...]
```

Have also added `force` for data, which can be used with or without `--use-test-data` (e.g. to replace test data with real data):

```sh
$ pyviz fetch-data --path=examples --force
[...]
Downloading NYC Taxi Data 1 of 1
[##                              ] 31000/375976 - 00:01:50
[...]
```

I'm not familiar with the various datasets or the download/extract mechanism. So, I'm not sure my changes are correct - would be great if someone familiar with the download/extract mechanism could review it, although if we go ahead with this, I will end up testing and reviewing it in practice later anyway (when using for pyviz).

I'm not sure what I've done will make sense for all datasets. In particular, the way I've done it here, there should be a corresponding entry in `test_files` for each entry in `files`, which might not make sense.

It's also possibly quite confusing that "the files on disk are a lie" after using `use_test_data`, but I can't think of another way that doesn't involve altering how data is loaded in examples.

Note that if there are no `test_files` for a given dataset, `files` are used instead (i.e. assumes that if no test files are supplied, it's because the original dataset is not large/problematic).

If this change seems ok, then the `examples` command should probably support the same options (passing through to `fetch-data`) before merging.

And then separately, nbsite will need some modifications (part of already planned modifications, e.g. https://github.com/pyviz/nbsite/issues/36).

I would be delighted to hear about an entirely better way of doing things (if it doesn't involve changing how examples load data).

### CODE REVIEW

**Comment by jbednar** [comment]
That all sounds reasonable to me.  A couple of ideas:

- One could imagine alleviating the problem that "the files on disk are a lie"  by adding a clean-up command to delete such files by going through all `files` in the .yml and deleting them if their filesize is the same as the declared `testfile`, i.e., if it's clear that they were copied from the given testfile and that the testfile is clearly redundant.  Could be done; not sure if it's worth the effort if this command will mainly be run by a CI system.
- Could we use directories on the filesystem to define the fallbacks, instead of needing an entry in the .yml? E.g. we can have real datasets in `data`, and any fallback smaller versions in some other directory like `.data_stubs` where the files have the same name as the real ones.  That way we wouldn't have to edit the .yml with stuff that is going to confuse users and be hard for us to maintain -- the only action required for there to be a substitute would be to commit the right file to git.

For completeness I should mention that I'm thinking of this mechanism as one part of comprehensive plan for providing the benefits of CI and automated builds while being able to handle large datasets and long runs that aren't practical to have in standard CI.  To check that we're aligned here, what I've been imagining is:

1. Automatic substitution of small test files (addressed by this PR), allowing a complete set of tests to be run on CI even when large datasets are not available.  This approach can be used by website builds, but the resulting site has to be thrown away, because it's just checking that things execute; the actual results shown are bogus due to the missing data.
2. Automatic substitution of already-run notebooks (addressed in some future PR, presumably on nbsite), allowing a complete website to be built and deployed by CI even though the files and runs involved would be too big for a CI job.
3. Automatic building on some explicit command of the notebooks needed for 2 and putting them somewhere the mechanism in 2 can find them.

The goal is for testing to be fully complete and automatic (albeit with small files), for website building to be fully complete and automatic (albeit with some notebooks not being re-run), and for generation of large notebooks to be fully complete and reproducible (albeit not running on a standard CI job, only by request (whether on a local machine or on some special CI job)).  Is that how you are thinking of things?  It's complex to describe, and annoying to have to do, but I think it's the only way to make maintaining these sites practical.

**Comment by jsignell** [comment]
To Do:
 - [x] Adding a clean-up command
   Scenarios: 
     1) Data is real file --> do nothing
     2) Data is test file --> delete
     3) File in test dir does not exist in data dir --> do nothing
     4) Test dir does not exist --> do nothing

   Notes:
   - very verbose
   - only reports on files found in `data/.data_stubs`
 - [x] Switch to using a dummy directory (`.data_stubs`) rather than requiring `dataset.yml` entries
   - should this be configurable ?
   - put in `data/.data_stubs`
 - [ ] Automatic building on some explicit command of the notebooks needed for 2 and putting them somewhere the mechanism in 2 can find them.

**Comment by jbednar** [comment]
Sounds great!

**Comment by jsignell** [comment]
Ok I have the tests running on CI now.

**Comment by jsignell** [comment]
>I'd prefer replacing 'foo' with 'test',

That makes sense. I started with a different structure where everything was temporary.

**Comment by jsignell** [comment]
I am updating the README and then this will be done.

**Comment by jsignell** [comment]
Ok this is good to merge. Should I do it and tag a release?

**Comment by jbednar** [comment]
I've merged it, and pleases do tag a release if you are ready!

**Comment by ceball** [comment]
Sorry this isn't documented anywhere @jsignell  but I think the process to follow for releasing is to always first tag a dev release (e.g. `v1.2.3a0` or similar), and if that turns out ok, then tag the same commit again with the release tag (e.g.` v1.2.3`). There are downsides to that process (e.g. takes more time before a release appears, not an obvious thing to have to do, and probably more...), but it helps catch most problems before tagging a release.

Creating a pyviz project release checklist is an open issue somewhere. It should just be a couple of steps (the above plus maybe writing release notes).

**Comment by ceball** [comment]
As for why the conda build failed, I will try to look later today if you haven't already figured it out by then (I just got the email notification about the failure).

**Comment by jsignell** [comment]
Ok I deleted those tags. I will try to figure out why it fails. I suspect the addition of pytest?

**Comment by jsignell** [comment]
Or possible changes to `pyctdev`

**Comment by ceball** [comment]
When I glanced at what you did, it looked right to me, and ought to have worked. If so, maybe a bug in pyctdev. I can't quite remember what I did for distutils/setuptools `tests_require` (the standard thing before pip) vs allowing the test dependencies to be specified in `extras_require`. I can look shortly (should be quick for me to figure out when I'm in front of a computer...don't think you want to be looking at that code yet...).

**Comment by jbednar** [comment]
Luckily I don't think anyone much cares what version number pyct has, so it's fine to keep increasing the version number as needed!

**Comment by ceball** [comment]
Yes, I think that's right in this case, but it's good to have the same process for all pyviz projects.

Meanwhile it's bad that I just keep saying it separately to people, instead of documenting it in a short release checklist.

**Comment by jsignell** [comment]
Ok I think the tags are gone. So you should feel free to reuse them. I am going to stop looking at it. Please let me know what you find though.

**Comment by jsignell** [comment]
Also let me know if there is some way to do a dry run locally.

**Comment by ceball** [comment]
I see the problem: it's something missing in pyct itself. (However, in a newer version of pyctdev, it's not required. But that newer version of pyctdev is not yet released. Sigh.) I'll make a PR.

**Comment by ceball** [comment]
Yes, you can run all of this stuff locally. That's one of the main aims of pyctdev: same commands locally as on CI systems. *However*, having said that, there are some things you have to be careful with right now, including environment stacking (was changing in conda while pyctdev was developed), and horrible interface/documentation.

**Comment by ceball** [comment]
See #67. Sorry to have wasted your time there @jsignell!

**Comment by ceball** [comment]
I don't really want to encourage people to use pyctdev locally yet, since the interface will change, and the general complaints will come in too fast ;) But, below's how it would go for pyct (untested, just typed out based on .travis file)...

Note 1: pyct's "default ecosystem" is currently pip. That means `doit` commands default to pip and tox rather than conda and conda build. You all probably want to change that to conda (I don't mind either way what the default is for a project). Currently the way to do that for a project is in its dodo.py file (see e.g. https://github.com/ioam/parambokeh/blob/master/dodo.py#L2). Meanwhile, without that, you either have to specify ecosystem=conda for every doit command as I will do below, or set an environment variable.

Note 2: pyctdev pins the version of conda-build. To avoid interfering with conda build you use for other work, you can probably start from a dedicated environment and then stack on top (rather than using your base/root environment).

```
# install pyctdev
$ conda install -c pyviz pyctdev && doit ecosystem=conda ecosystem_setup
#
# build pyct-core and run the 'build_examples' tests (defined in tox.ini) with python 3.6 
$ doit ecosystem=conda package_build --recipe=core --test-python=py36 --test-group=build_examples -c pyviz
# 
# build pyct and run the 'cmd_examples' tests (defined in tox.ini) with python 2.7 
$ doit ecosystem=conda package_build --test-python=py27 --test-group=cmd_examples -c pyviz
```

Note 3: the next version of pyctdev will change the above (e.g. now supports multiple outputs from one recipe).

**Comment by jsignell** [comment]
Ok thanks @ceball I was wondering how those meta.yaml factored in. I will tag a release now.

**Comment by jsignell** [comment]
Dang it it failed again. https://travis-ci.org/pyviz/pyct/jobs/449096191. Maybe it's python 2.7?

**Comment by jsignell** [comment]
I tweaked the command and made the tests pass on 2.7 https://github.com/pyviz/pyct/pull/68

**Comment by jsignell** [comment]
Ok I got the build_package failure locally. Should be able to debug better from here.

**Comment by ceball** [comment]
@jsignell it just occurred to me that pyargs is missing from the pytest
config in tox.ini (a pytest option; see datashader for an example). I think
you asked if any of that was necessary, but I forgot to respond to that
part. Sorry!

**Comment by jsignell** [comment]
Yeah I realized that too.

**Comment by jsignell** [comment]
Just to circle back: successful release!

**Pull request merged**
