### PR TITLE
Making all test files temporary

### PR DESCRIPTION
**Pull request by jsignell**
Phew. The build passes for me locally now. The issue was that the example files weren't being copied over into the package build. In other projects we use pyct to copy the examples during the package building (https://github.com/pyviz/datashader/blob/17629bd82708499beb0b990d7f092fd68ea3d172/tox.ini#L41). 

This wasn't as straightforward in pyct because there are two differnt packages that are getting built and pyct-core doesn't have access to pyct.cmd  so can't do the copying.

Using purely temporary files is probably a cleaner approach anyways.

### CODE REVIEW

**Comment by jsignell** [comment]
I am going to merge this when it passes and tag 🤞

**Comment by jbednar** [comment]
I don't know if this is relevant or not, because I could be talking about something different from what you are discussing, but we do deliberately copy the examples into packages when building them, because that is the only reliable way we have found for the examples to be available for conda and pip installs -- any other location for them fails in certain cases.

**Comment by jsignell** [comment]
>we do deliberately copy the examples into packages when building them

Yes that is what I was pointing to here: https://github.com/pyviz/datashader/blob/17629bd82708499beb0b990d7f092fd68ea3d172/tox.ini#L41

It doesn't work in this case because we are building a pyct-core package that doesn't have access to pyct commands.

**Comment by ceball** [comment]
I'm not sure which example files you're referring to, for pyct. Does pyct have example files? Do you instead maybe mean files required to run the tests? Sorry I have not followed closely.

**Comment by ceball** [comment]
Sorry if I'm explaining something everyone knows here, but to try to clarify something...there's:
  1. copying non-python files into packages
  2. "copying examples into packages"

1 is the normal python packaging mechanism, unrelated to pyct. Files that are not normally included by default in distributions (distribution = sdist, wheel, etc) can be included via rules in MANIFEST.in (along with having `include_package_data=True` in setup.py or setup.cfg). That is, if you have `pyct/tests/some_file.txt`, it won't be included in e.g. the sdist unless you have a rule in MANIFEST.in (and won't be subsequently copied to the user's machine when the sdist is installed unless you have `inlcude_package_data=True`). 

2 was the source of some pyviz controversy ;) The above approach in 1 only supports putting a file in the same place in the dist as it is in the package before the dist is built. So to have e.g. package/examples/a.ipynb in the dist, you have to have package/examples/a.ipynb in the source repository. `pyct.build` is about copying some files (e.g. notebooks) from somewhere inside the git source repository to somewhere different at package time. E.g. copying files from /examples/ in the git repository to /package/examples/ at packaging time, so that /package/examples/ exists in the dist. 

Either way, having the examples in the package allows them to later be found reliably (e.g. so users can get a copy of the files), because they can be found relative to the imported module. In the future, there might be an entirely better way that works for conda and pip installs.

**Comment by ceball** [comment]
And yes, it's confusing that: 

  * with pip install pyct you get the minimum dependencies (i.e. only support for pyct.build), and pip install pyct[cmd] you get the extra dependencies required for the user commands (i.e. support for pyct.cmd also)

  * whereas with conda install pyct you get the maximum dependencies (i.e. support for pyct.build and pyct.cmd), and conda install pyct-core gets you the minimum dependencies (support for pyct.cmd only).

pyct could really just be one package, because the dependencies aren't a big problem, and package builders don't have trouble installing dependencies anyway`*`. However, pyct became my practice project for conda support of split packages/multiple outputs from one recipe...


`*` In the past, before wheels/conda packages, everyone was kind of a package builder and executed your setup.py, so build dependencies did matter more sometimes.

**Pull request merged**
